cache_dir: data
output_dir: output
# te_api_key: "user:token"   # si tu veux la poser ici et exporter aussi TE_API_KEY en env
paths:
  macro_csv: data/macro_dashboard.csv
  output_macro: output/macro_dashboard_legacy_style.png

rates:
  start: "2020-01-01"
  tickers:
    "Taux US 2 ans": "^UST2Y"
    "Taux US 10 ans": "^TNX"
    "Taux All. 2 ans": "DE2Y.BOND"
    "Taux All. 10 ans": "DE10Y.BOND"

credit:
  start: "2020-01-01"
  tickers:
    "iTraxx Europe": "^ITRXE"
    "iTraxx Xover": "^ITRXXO"
    "CDX NA IG": "^CDXIG"
    "CDX NA HY": "^CDXHY"
