cache_dir: data
output_dir: output
# te_api_key: "user:token"   # si tu veux la poser ici et exporter aussi TE_API_KEY en env
paths:
  macro_csv: data/macro_dashboard.csv
  output_macro: output/macro_dashboard_legacy_style.png
